name: Translate README

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdown-translator
        run: npm install -g markdown-translator

      - name: Translate README
        run: |
          md-translator set --key ${{ secrets.AZURE_TRANSLATOR_KEY }}
          md-translator set --region westeurope
          md-translator translate --src README.md --dest README-FR.md --from en-US --to fr-FR
          md-translator translate --src README.md --dest README-DE.md --from en-US --to de-DE
          md-translator translate --src README.md --dest README-NL.md --from en-US --to nl-NL
          md-translator translate --src README.md --dest README-TW.md --from en-US --to zh-TW
          md-translator translate --src README.md --dest README-ZH.md --from en-US --to zh-CN

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README-FR.md README-DE.md README-NL.md README-TW.md README-ZH.md
          git commit -m "Translate README.md"
          git push